
# 1.1 四状态枚举量 0x80
g_sqle_tab0x80 = {
    'VCU_BatPwrEn' :           1,  
    'VCU_DCDC24PwrEn' :        2,  
    'VCU_DCAC_SPwrEn' :        3,  
    'VCU_DCAC_BPwrEn' :        4,  
    'VCU_PTCContaEn' :         5,  
    'VCU_BatNoChrgEn' :        6,  
    'VCU_ACCMPwrEn' :          7,  
    'VCU_MainContaPEn' :       8,  
    'VCU_MotPwrEn' :           9,  
    'VCU_LockFuncActiveSts' :  10, 
    'VCU_SpdLimitSts' :        11, 
    'MCU_MotWorkMode' :        12, 
    'MCU_PTCContaSts' :        13, 
    'MCU_ContaPSts' :          14, 
    'MCU_AuxHVContaSts' :      15, 
    'MCU_ACCMContaSts' :       16, 
    'BMS_ContaNSts' :          17, 
    'BMS_InsErrSts' :          18, 
    'BMS_ChrgMode' :           19, 
    'BMS_ChrgContaP1Sts' :     20, 
    'BMS_ChrgContaN1Sts' :     21, 
    'TMSModeSet' :             22, 
    'BTMS_WorkMode' :          23, 
    'BTMS_RelaySts' :          24
};

# 1.3 十六状态枚举量 0x82
g_sqle_tab0x82 = {
    'VCU_VehSts' :                  1,  
    'VCU_ErrSts' :                  2,  
    'VCU_ShiftLevel' :              3,  
    'MCU_SysSts' :                  4,  
    'MCU_ErrSts' :                  5,  
    'BMS_SysSts' :                  6,  
    'BMS_ErrSts' :                  7,  
    'BMS_ChrgSts' :                 8,  
    'BTMS_SysSts' :                 9,  
    'BTMS_ErrSts' :                 10, 
    'DCAC_S_SysSts' :               11, 
    'DCAC_S_ErrSts' :               12, 
    'DCAC_B_SysSts' :               13, 
    'DCAC_B_ErrSts' :               14, 
    'ACCM_SysSts' :                 15, 
    'ACCM_ErrSts' :                 16, 
    'DCDC_SysSts' :                 17, 
    'DCDC_ErrSts' :                 18, 
};

/// 1.4 八位模拟数据 0x83
g_sqle_tab0x83 = {
    'VCU_AccPedPos' :                 1,  
    'VCU_BrkPedPos' :                 2,  
    'VCU_StartSts' :                  3,  
    'VCU_PwrMode' :                   4,  
    'VCU_ChrgSts' :                   5,  
    'VCU_DCDCSts' :                   6,  
    'VCU_MaxAlarmLevel' :             7,  
    'SLU_GearReq' :                   8,  
    'MCU_MotWorkSts' :                9,  
    'MCU_MotTotalNum' :               10, 
    'MCU_MotIndex' :                  11, 
    'MCU_MotTemp' :                   12, 
    'MCU_ECUTemp' :                   13, 
    'BMS_SOC' :                       14, 
    'BatM_IdxMaxVolt' :               15, 
    'BatM_IdxMinVolt' :               16, 
    'BatM_TempMax' :                  17, 
    'BatM_IdxMaxTemp' :               18, 
    'BatM_IdxMaxTempSens' :           19, 
    'BatM_TempMin' :                  20, 
    'BatM_IdxMinTemp' :               21, 
    'BatM_IdxMinTempSens' :           22, 
    'BMS_SubSysNum' :                 23, 
    'BMS_SubSysIdx' :                 24, 
    'BMS_VoltFrameIdx' :              25, 
    'BMS_TempPackIdx' :               26,  
    'BMS_TempFrameIdx' :              27,  
    'BMS_TempPackIdx' :               28,  
    'BMS_PrbXTemp' :                  29,  
    'BMS_PrbYTemp' :                  30,  
    'BMS_PrbZTemp' :                  31,  
    'BMS_PrbUTemp' :                  32,  
    'BMS_PrbVTemp' :                  33,  
    'BMS_PrbWTemp' :                  34,  
};

# 1.5 十六位模拟数据 0x84
g_sqle_tab0x84 = {
    'VCU_VehSpd' :                       1,  
    'MCU_DCCurrent' :                    2,  
    'MCU_DCVoltage' :                    3,  
    'MCU_MotSpd' :                       4,  
    'MCU_MotTq' :                        5,  
    'BMS_Voltage' :                      6,  
    'BMS_Current' :                      7,  
    'BatC_VoltMax' :                     8,  
    'BatC_IdxMaxVolt' :                  9,  
    'BatC_VoltMin' :                     10, 
    'BatC_IdxMinVolt' :                  11, 
    'Bat_TotalConsume' :                 12, 
    'Bat_ResP2Gnd' :                     13, 
    'Bat_ResN2Gnd' :                     14, 
    'BMS_SubSysCellNum' :                15, 
    'BMS_SubSysTempPrbNum' :             16, 
    'BMS_CellXVolt' :                    17, 
    'BMS_CellYVolt' :                    18, 
    'BMS_CellZVolt' :                    19, 
    
};

# 1.6 一位开关量 0x85
g_sqle_tab0x85 = {
    'VCU_VehSpd' :                        1,    
    'VCU_DrvActive' :                     2,   
    'Veh_Err21' :                         3,   
    'Veh_Err22' :                         4,   
    'Veh_Err23' :                         5,   
    'Veh_Err24' :                         6,   
    'Veh_Err25' :                         7,   
    'Veh_Err26' :                         8,   
    'Veh_Err27' :                         9,   
    'Veh_Err28' :                         10,  
    'Veh_Err31' :                         11,  
    'Veh_Err32' :                         12,  
    'Veh_Err33' :                         13,  
    'Veh_Err34' :                         14,  
    'Veh_Err35' :                         15,  
    'Veh_Err36' :                         16,  
    'Veh_Err37' :                         17,  
    'Veh_Err38' :                         18,  
    'Veh_Err41' :                         19,  
    'Veh_Err42' :                         20,  
    'Veh_Err43' :                         21,  
    'BMS_TempDiffAlarm' :                 22,   
    'BMS_HighTempAlarm' :                 23,   
    'BMS_OverVoltAlarm' :                 24,   
    'BMS_UnderVoltAlarm' :                25,   
    'BMS_SOCLowAlarm' :                   26,   
    'BMS_CellOverVoltAlarm' :             27,   
    'BMS_CellUnderVoltAlarm' :            28,   
    'BMS_SOCHighAlarm' :                  29,   
    'BMS_SOCJumpAlarm' :                  30,   
    'BMS_REESSMismatchAlarm' :            31,   
    'BMS_CellPoorConsistencyAlarm' :      32,   
    'BMS_InsulationAlarm' :               33,   
    'BMS_HVILStsAlarm' :                  34,   
    'BMS_OverChargeAlarm' :               35,   
    'BMS_Err31' :                         36,   
    'BMS_Err32' :                         37,   
    'BMS_Err33' :                         38,   
    'BMS_Err34' :                         39,   
    'BMS_Err35' :                         40,   
    'BMS_Err36' :                         41,   
    'BMS_Err37' :                         42,   
    'BMS_Err38' :                         43,   
    'BMS_Err41' :                         44,   
    'BMS_Err42' :                         45,   
    'BMS_Err43' :                         46,   
    'BMS_Err44' :                         47,   
    'BMS_Err45' :                         48,   
    'BMS_Err46' :                         49,   
    'BMS_Err47' :                         50,   
    'BMS_Err48' :                         51,   
    'BMS_Err51' :                         52,   
    'BMS_Err52' :                         53,   
    'BMS_Err53' :                         54,   
    'BMS_Err54' :                         55,   
    'BMS_Err55' :                         56,   
    'BMS_Err56' :                         57,   
    'BMS_Err57' :                         58,   
    'BMS_Err58' :                         59,   
    'BMS_Err61' :                         60,   
};

# 1.8 其他信号 0x87
g_sqle_tab0x87 = {
    'VCU_Odometer' :    1,
};
